Validate invoker response
janis-commerce/microservice-call pull request #24
Opened 2023-12-21 11:31 UTC by tomascanales

**LINK AL TICKET**
https://janiscommerce.atlassian.net/browse/JCN-463
https://janiscommerce.atlassian.net/browse/JCN-464

**DESCRIPCIÓN DEL REQUERIMIENTO**
Manejar errores que puede devolver Invoker.serviceCall

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se agrego una validacion por si viene la propiedad functionError o errorMessage dentro del payload, tambien se valida el payload tiene baseUrl, path y method.

**Changelog**

```
### Added

- Validations for the Invoker response to the Discovery GetEnpoint call
```

2023-12-21 20:16 UTC, Alejandro-Gonzalez requested changes

2023-12-21 20:16 UTC, Alejandro-Gonzalez commented on tests/microservice-call.js
> +		it('Should throw an error if it has an error message', async () => {
@tomascanales te agregas un test mas para cuando tenemos functionError

2023-12-28 19:29 UTC, Alejandro-Gonzalez approved these changes

2024-01-05 22:23 UTC, gastonpereyra approved these changes

2024-01-12 15:03 UTC, merged